-- 20 Pokémon card inserts
INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat,
                       cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Bulbasaur', 'Seed Pokémon', 'Vine Whip', '20', 'Fire', 'Water', '1',
 1, 1, 1, 1),
(50, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', 'Grass', '1',
 4, 1, 2, 1),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '20', 'Lightning', 'Fire', '1',
 7, 1, 3, 1),
(40, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', 'Steel', '1',
 25, 1, 4, 1),
(60, 'Jigglypuff', 'Balloon Pokémon', 'Pound', '20', 'Fighting', 'Psychic', '1',
 54, 1, 7, 1),
(90, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', 'Fighting', '1',
 10, 2, 1, 1),
(100, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '50', 'Psychic', 'None', '2',
 7, 3, 6, 1),
(80, 'Gengar', 'Shadow Pokémon', 'Nightmare', '40', 'Psychic', 'Fighting', '2',
 5, 3, 5, 3),
(70, 'Eevee', 'Evolution Pokémon', 'Quick Attack', '20', 'Fighting', 'Psychic', '1',
 55, 2, 7, 1),
(120, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '50', 'Fighting', 'Psychic', '4',
 11, 2, 7, 1),
(90, 'Machop', 'Superpower Pokémon', 'Low Kick', '30', 'Psychic', 'None', '1',
 66, 1, 6, 1),
(110, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', 'None', '2',
 67, 1, 6, 2),
(130, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', 'None', '3',
 68, 1, 6, 3),
(70, 'Oddish', 'Weed Pokémon', 'Absorb', '20', 'Fire', 'Water', '1',
 58, 2, 1, 1),
(100, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '30', 'Fire', 'Water', '2',
 59, 2, 1, 2),
(130, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '50', 'Fire', 'Water', '3',
 60, 2, 1, 3),
(90, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '30', 'Grass', 'None', '1',
 9, 3, 6, 1),
(120, 'Kabutops', 'Shellfish Pokémon', 'Slash', '50', 'Grass', 'None', '2',
 10, 3, 6, 2),
(80, 'Zapdos', 'Electric Pokémon', 'Thunder', '60', 'Rock', 'Fighting', '3',
 15, 1, 4, 1),
(100, 'Mewtwo', 'Genetic Pokémon', 'Psychic', '60', 'Psychic', 'None', '3',
 10, 1, 5, 1);
